// Code generated by entimport, DO NOT EDIT.

package schema

import (
	"time"
	"entgo.io/ent"
	"entgo.io/ent/schema"
	"entgo.io/ent/schema/field"
)

type ContactSubmission struct {
	ent.Schema
}

func (ContactSubmission) Fields() []ent.Field {
	return []ent.Field{
		field.String("name").NotEmpty(),
		field.String("phone").NotEmpty(),
		field.String("email").NotEmpty(),
		field.String("subject").NotEmpty(),
		field.Text("message").NotEmpty(),
		field.Time("submitted_at").Default(time.Now),
	}
}
func (ContactSubmission) Edges() []ent.Edge {
	return nil
}
func (ContactSubmission) Annotations() []schema.Annotation {
	return nil
}
