// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// ContactSubmission is the predicate function for contactsubmission builders.
type ContactSubmission func(*sql.Selector)

// SchemaMigration is the predicate function for schemamigration builders.
type SchemaMigration func(*sql.Selector)
