// Code generated by ent, DO NOT EDIT.

package ent

import (
	"4th_Assignment/ent/contactsubmission"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// ContactSubmission is the model entity for the ContactSubmission schema.
type ContactSubmission struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Phone holds the value of the "phone" field.
	Phone string `json:"phone,omitempty"`
	// Email holds the value of the "email" field.
	Email string `json:"email,omitempty"`
	// Subject holds the value of the "subject" field.
	Subject string `json:"subject,omitempty"`
	// Message holds the value of the "message" field.
	Message string `json:"message,omitempty"`
	// SubmittedAt holds the value of the "submitted_at" field.
	SubmittedAt  time.Time `json:"submitted_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ContactSubmission) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case contactsubmission.FieldID:
			values[i] = new(sql.NullInt64)
		case contactsubmission.FieldName, contactsubmission.FieldPhone, contactsubmission.FieldEmail, contactsubmission.FieldSubject, contactsubmission.FieldMessage:
			values[i] = new(sql.NullString)
		case contactsubmission.FieldSubmittedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ContactSubmission fields.
func (cs *ContactSubmission) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case contactsubmission.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			cs.ID = int(value.Int64)
		case contactsubmission.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				cs.Name = value.String
			}
		case contactsubmission.FieldPhone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field phone", values[i])
			} else if value.Valid {
				cs.Phone = value.String
			}
		case contactsubmission.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				cs.Email = value.String
			}
		case contactsubmission.FieldSubject:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subject", values[i])
			} else if value.Valid {
				cs.Subject = value.String
			}
		case contactsubmission.FieldMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message", values[i])
			} else if value.Valid {
				cs.Message = value.String
			}
		case contactsubmission.FieldSubmittedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field submitted_at", values[i])
			} else if value.Valid {
				cs.SubmittedAt = value.Time
			}
		default:
			cs.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ContactSubmission.
// This includes values selected through modifiers, order, etc.
func (cs *ContactSubmission) Value(name string) (ent.Value, error) {
	return cs.selectValues.Get(name)
}

// Update returns a builder for updating this ContactSubmission.
// Note that you need to call ContactSubmission.Unwrap() before calling this method if this ContactSubmission
// was returned from a transaction, and the transaction was committed or rolled back.
func (cs *ContactSubmission) Update() *ContactSubmissionUpdateOne {
	return NewContactSubmissionClient(cs.config).UpdateOne(cs)
}

// Unwrap unwraps the ContactSubmission entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (cs *ContactSubmission) Unwrap() *ContactSubmission {
	_tx, ok := cs.config.driver.(*txDriver)
	if !ok {
		panic("ent: ContactSubmission is not a transactional entity")
	}
	cs.config.driver = _tx.drv
	return cs
}

// String implements the fmt.Stringer.
func (cs *ContactSubmission) String() string {
	var builder strings.Builder
	builder.WriteString("ContactSubmission(")
	builder.WriteString(fmt.Sprintf("id=%v, ", cs.ID))
	builder.WriteString("name=")
	builder.WriteString(cs.Name)
	builder.WriteString(", ")
	builder.WriteString("phone=")
	builder.WriteString(cs.Phone)
	builder.WriteString(", ")
	builder.WriteString("email=")
	builder.WriteString(cs.Email)
	builder.WriteString(", ")
	builder.WriteString("subject=")
	builder.WriteString(cs.Subject)
	builder.WriteString(", ")
	builder.WriteString("message=")
	builder.WriteString(cs.Message)
	builder.WriteString(", ")
	builder.WriteString("submitted_at=")
	builder.WriteString(cs.SubmittedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ContactSubmissions is a parsable slice of ContactSubmission.
type ContactSubmissions []*ContactSubmission
