// Code generated by ent, DO NOT EDIT.

package ent

import (
	"4th_Assignment/ent/contactsubmission"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ContactSubmissionCreate is the builder for creating a ContactSubmission entity.
type ContactSubmissionCreate struct {
	config
	mutation *ContactSubmissionMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (csc *ContactSubmissionCreate) SetName(s string) *ContactSubmissionCreate {
	csc.mutation.SetName(s)
	return csc
}

// SetPhone sets the "phone" field.
func (csc *ContactSubmissionCreate) SetPhone(s string) *ContactSubmissionCreate {
	csc.mutation.SetPhone(s)
	return csc
}

// SetEmail sets the "email" field.
func (csc *ContactSubmissionCreate) SetEmail(s string) *ContactSubmissionCreate {
	csc.mutation.SetEmail(s)
	return csc
}

// SetSubject sets the "subject" field.
func (csc *ContactSubmissionCreate) SetSubject(s string) *ContactSubmissionCreate {
	csc.mutation.SetSubject(s)
	return csc
}

// SetMessage sets the "message" field.
func (csc *ContactSubmissionCreate) SetMessage(s string) *ContactSubmissionCreate {
	csc.mutation.SetMessage(s)
	return csc
}

// SetSubmittedAt sets the "submitted_at" field.
func (csc *ContactSubmissionCreate) SetSubmittedAt(t time.Time) *ContactSubmissionCreate {
	csc.mutation.SetSubmittedAt(t)
	return csc
}

// SetNillableSubmittedAt sets the "submitted_at" field if the given value is not nil.
func (csc *ContactSubmissionCreate) SetNillableSubmittedAt(t *time.Time) *ContactSubmissionCreate {
	if t != nil {
		csc.SetSubmittedAt(*t)
	}
	return csc
}

// Mutation returns the ContactSubmissionMutation object of the builder.
func (csc *ContactSubmissionCreate) Mutation() *ContactSubmissionMutation {
	return csc.mutation
}

// Save creates the ContactSubmission in the database.
func (csc *ContactSubmissionCreate) Save(ctx context.Context) (*ContactSubmission, error) {
	csc.defaults()
	return withHooks(ctx, csc.sqlSave, csc.mutation, csc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (csc *ContactSubmissionCreate) SaveX(ctx context.Context) *ContactSubmission {
	v, err := csc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (csc *ContactSubmissionCreate) Exec(ctx context.Context) error {
	_, err := csc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (csc *ContactSubmissionCreate) ExecX(ctx context.Context) {
	if err := csc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (csc *ContactSubmissionCreate) defaults() {
	if _, ok := csc.mutation.SubmittedAt(); !ok {
		v := contactsubmission.DefaultSubmittedAt()
		csc.mutation.SetSubmittedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (csc *ContactSubmissionCreate) check() error {
	if _, ok := csc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "ContactSubmission.name"`)}
	}
	if v, ok := csc.mutation.Name(); ok {
		if err := contactsubmission.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "ContactSubmission.name": %w`, err)}
		}
	}
	if _, ok := csc.mutation.Phone(); !ok {
		return &ValidationError{Name: "phone", err: errors.New(`ent: missing required field "ContactSubmission.phone"`)}
	}
	if v, ok := csc.mutation.Phone(); ok {
		if err := contactsubmission.PhoneValidator(v); err != nil {
			return &ValidationError{Name: "phone", err: fmt.Errorf(`ent: validator failed for field "ContactSubmission.phone": %w`, err)}
		}
	}
	if _, ok := csc.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "ContactSubmission.email"`)}
	}
	if v, ok := csc.mutation.Email(); ok {
		if err := contactsubmission.EmailValidator(v); err != nil {
			return &ValidationError{Name: "email", err: fmt.Errorf(`ent: validator failed for field "ContactSubmission.email": %w`, err)}
		}
	}
	if _, ok := csc.mutation.Subject(); !ok {
		return &ValidationError{Name: "subject", err: errors.New(`ent: missing required field "ContactSubmission.subject"`)}
	}
	if v, ok := csc.mutation.Subject(); ok {
		if err := contactsubmission.SubjectValidator(v); err != nil {
			return &ValidationError{Name: "subject", err: fmt.Errorf(`ent: validator failed for field "ContactSubmission.subject": %w`, err)}
		}
	}
	if _, ok := csc.mutation.Message(); !ok {
		return &ValidationError{Name: "message", err: errors.New(`ent: missing required field "ContactSubmission.message"`)}
	}
	if v, ok := csc.mutation.Message(); ok {
		if err := contactsubmission.MessageValidator(v); err != nil {
			return &ValidationError{Name: "message", err: fmt.Errorf(`ent: validator failed for field "ContactSubmission.message": %w`, err)}
		}
	}
	if _, ok := csc.mutation.SubmittedAt(); !ok {
		return &ValidationError{Name: "submitted_at", err: errors.New(`ent: missing required field "ContactSubmission.submitted_at"`)}
	}
	return nil
}

func (csc *ContactSubmissionCreate) sqlSave(ctx context.Context) (*ContactSubmission, error) {
	if err := csc.check(); err != nil {
		return nil, err
	}
	_node, _spec := csc.createSpec()
	if err := sqlgraph.CreateNode(ctx, csc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	csc.mutation.id = &_node.ID
	csc.mutation.done = true
	return _node, nil
}

func (csc *ContactSubmissionCreate) createSpec() (*ContactSubmission, *sqlgraph.CreateSpec) {
	var (
		_node = &ContactSubmission{config: csc.config}
		_spec = sqlgraph.NewCreateSpec(contactsubmission.Table, sqlgraph.NewFieldSpec(contactsubmission.FieldID, field.TypeInt))
	)
	if value, ok := csc.mutation.Name(); ok {
		_spec.SetField(contactsubmission.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := csc.mutation.Phone(); ok {
		_spec.SetField(contactsubmission.FieldPhone, field.TypeString, value)
		_node.Phone = value
	}
	if value, ok := csc.mutation.Email(); ok {
		_spec.SetField(contactsubmission.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := csc.mutation.Subject(); ok {
		_spec.SetField(contactsubmission.FieldSubject, field.TypeString, value)
		_node.Subject = value
	}
	if value, ok := csc.mutation.Message(); ok {
		_spec.SetField(contactsubmission.FieldMessage, field.TypeString, value)
		_node.Message = value
	}
	if value, ok := csc.mutation.SubmittedAt(); ok {
		_spec.SetField(contactsubmission.FieldSubmittedAt, field.TypeTime, value)
		_node.SubmittedAt = value
	}
	return _node, _spec
}

// ContactSubmissionCreateBulk is the builder for creating many ContactSubmission entities in bulk.
type ContactSubmissionCreateBulk struct {
	config
	err      error
	builders []*ContactSubmissionCreate
}

// Save creates the ContactSubmission entities in the database.
func (cscb *ContactSubmissionCreateBulk) Save(ctx context.Context) ([]*ContactSubmission, error) {
	if cscb.err != nil {
		return nil, cscb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(cscb.builders))
	nodes := make([]*ContactSubmission, len(cscb.builders))
	mutators := make([]Mutator, len(cscb.builders))
	for i := range cscb.builders {
		func(i int, root context.Context) {
			builder := cscb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ContactSubmissionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, cscb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, cscb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, cscb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (cscb *ContactSubmissionCreateBulk) SaveX(ctx context.Context) []*ContactSubmission {
	v, err := cscb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cscb *ContactSubmissionCreateBulk) Exec(ctx context.Context) error {
	_, err := cscb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cscb *ContactSubmissionCreateBulk) ExecX(ctx context.Context) {
	if err := cscb.Exec(ctx); err != nil {
		panic(err)
	}
}
