// Code generated by ent, DO NOT EDIT.

package ent

import (
	"4th_Assignment/ent/contactsubmission"
	"4th_Assignment/ent/predicate"
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// ContactSubmissionDelete is the builder for deleting a ContactSubmission entity.
type ContactSubmissionDelete struct {
	config
	hooks    []Hook
	mutation *ContactSubmissionMutation
}

// Where appends a list predicates to the ContactSubmissionDelete builder.
func (csd *ContactSubmissionDelete) Where(ps ...predicate.ContactSubmission) *ContactSubmissionDelete {
	csd.mutation.Where(ps...)
	return csd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (csd *ContactSubmissionDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, csd.sqlExec, csd.mutation, csd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (csd *ContactSubmissionDelete) ExecX(ctx context.Context) int {
	n, err := csd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (csd *ContactSubmissionDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(contactsubmission.Table, sqlgraph.NewFieldSpec(contactsubmission.FieldID, field.TypeInt))
	if ps := csd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, csd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	csd.mutation.done = true
	return affected, err
}

// ContactSubmissionDeleteOne is the builder for deleting a single ContactSubmission entity.
type ContactSubmissionDeleteOne struct {
	csd *ContactSubmissionDelete
}

// Where appends a list predicates to the ContactSubmissionDelete builder.
func (csdo *ContactSubmissionDeleteOne) Where(ps ...predicate.ContactSubmission) *ContactSubmissionDeleteOne {
	csdo.csd.mutation.Where(ps...)
	return csdo
}

// Exec executes the deletion query.
func (csdo *ContactSubmissionDeleteOne) Exec(ctx context.Context) error {
	n, err := csdo.csd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{contactsubmission.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (csdo *ContactSubmissionDeleteOne) ExecX(ctx context.Context) {
	if err := csdo.Exec(ctx); err != nil {
		panic(err)
	}
}
