// Code generated by ent, DO NOT EDIT.

package ent

import (
	"4th_Assignment/ent/contactsubmission"
	"4th_Assignment/ent/schema"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	contactsubmissionFields := schema.ContactSubmission{}.Fields()
	_ = contactsubmissionFields
	// contactsubmissionDescName is the schema descriptor for name field.
	contactsubmissionDescName := contactsubmissionFields[0].Descriptor()
	// contactsubmission.NameValidator is a validator for the "name" field. It is called by the builders before save.
	contactsubmission.NameValidator = contactsubmissionDescName.Validators[0].(func(string) error)
	// contactsubmissionDescPhone is the schema descriptor for phone field.
	contactsubmissionDescPhone := contactsubmissionFields[1].Descriptor()
	// contactsubmission.PhoneValidator is a validator for the "phone" field. It is called by the builders before save.
	contactsubmission.PhoneValidator = contactsubmissionDescPhone.Validators[0].(func(string) error)
	// contactsubmissionDescEmail is the schema descriptor for email field.
	contactsubmissionDescEmail := contactsubmissionFields[2].Descriptor()
	// contactsubmission.EmailValidator is a validator for the "email" field. It is called by the builders before save.
	contactsubmission.EmailValidator = contactsubmissionDescEmail.Validators[0].(func(string) error)
	// contactsubmissionDescSubject is the schema descriptor for subject field.
	contactsubmissionDescSubject := contactsubmissionFields[3].Descriptor()
	// contactsubmission.SubjectValidator is a validator for the "subject" field. It is called by the builders before save.
	contactsubmission.SubjectValidator = contactsubmissionDescSubject.Validators[0].(func(string) error)
	// contactsubmissionDescMessage is the schema descriptor for message field.
	contactsubmissionDescMessage := contactsubmissionFields[4].Descriptor()
	// contactsubmission.MessageValidator is a validator for the "message" field. It is called by the builders before save.
	contactsubmission.MessageValidator = contactsubmissionDescMessage.Validators[0].(func(string) error)
	// contactsubmissionDescSubmittedAt is the schema descriptor for submitted_at field.
	contactsubmissionDescSubmittedAt := contactsubmissionFields[5].Descriptor()
	// contactsubmission.DefaultSubmittedAt holds the default value on creation for the submitted_at field.
	contactsubmission.DefaultSubmittedAt = contactsubmissionDescSubmittedAt.Default.(func() time.Time)
}
